### ISSUE TITLE
Light colours not being set with sync

### ISSUE THREAD

**Issue by sborg-ms** [isaacrlevin/presencelight#273] opened 2021-02-18 22:07 UTC
latest nightly - v3.7.43.0

After install the saw the setup as per
![image](https://user-images.githubusercontent.com/67351620/108427708-b2c4d300-7291-11eb-9eef-373c48dbc072.png)

Then manually set each colour to suit - but the lifx still not syncing and showing teams status colours.

log extract:
{"Timestamp":"2021-02-19T09:02:43.9751071+11:00","Level":"Information","MessageTemplate":"PresenceLight Running in Teams Mode - MainWindow.xaml:InteractWithLights Line: 821","Properties":{"SourceContext":"PresenceLight.MainWindow","LineNumber":821,"FilePath":"D:\\a\\presencelight\\presencelight\\src\\DesktopClient\\PresenceLight\\MainWindow.xaml.cs","MemberName":"InteractWithLights","Application":"PresenceLight"}}
{"Timestamp":"2021-02-19T09:02:44.3215839+11:00","Level":"Error","MessageTemplate":"Error Occured Setting Color - LifxService:SetColor Line: 299","Exception":"System.NullReferenceException: Object reference not set to an instance of an object.\r\n   at PresenceLight.Core.LIFXService.SetColor(String availability, String activity, String lightId, String apiKey) in D:\\a\\presencelight\\presencelight\\src\\PresenceLight.Core\\Lights\\LifxServices\\LifxService.cs:line 302","Properties":{"SourceContext":"PresenceLight.Core.LIFXService","LineNumber":299,"FilePath":"D:\\a\\presencelight\\presencelight\\src\\PresenceLight.Core\\Lights\\LifxServices\\LifxService.cs","MemberName":"SetColor","Application":"PresenceLight"}}
{"Timestamp":"2021-02-19T09:02:44.3229864+11:00","Level":"Error","MessageTemplate":"Error Occurred - MainWindow.xaml:SetColor Line: 366","Exception":"System.NullReferenceException: Object reference not set to an instance of an object.\r\n   at PresenceLight.Core.LIFXService.SetColor(String availability, String activity, String lightId, String apiKey) in D:\\a\\presencelight\\presencelight\\src\\PresenceLight.Core\\Lights\\LifxServices\\LifxService.cs:line 302\r\n   at PresenceLight.Core.LifxServices.SetColorHandler.Handle(SetColorCommand command, CancellationToken cancellationToken) in D:\\a\\presencelight\\presencelight\\src\\PresenceLight.Core\\Lights\\LifxServices\\SetColor\\SetColorHandler.cs:line 26\r\n   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)\r\n   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)\r\n   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)\r\n   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)\r\n   at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)\r\n   at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)\r\n   at PresenceLight.MainWindow.SetColor(String color, String activity) in D:\\a\\presencelight\\presencelight\\src\\DesktopClient\\PresenceLight\\MainWindow.xaml.cs:line 370","Properties":{"SourceContext":"PresenceLight.MainWindow","LineNumber":366,"FilePath":"D:\\a\\presencelight\\presencelight\\src\\DesktopClient\\PresenceLight\\MainWindow.xaml.cs","MemberName":"SetColor","Application":"PresenceLight"}}

**Comment by isaacrlevin** [comment] 2021-02-19 14:16
I just downloaded the latest nightly and was not able to reproduce this. Did you uninstall the app, restart and reinstall

**Comment by sborg-ms** [comment] 2021-02-20 23:24
Uninstalled. Rebooted. Reinstalled latest nightly 3.7.45.0 and Teams syncing seems ok. Will test more during business hours :)

**Comment by isaacrlevin** [comment] 2021-02-21 22:51
closing

**Closed by isaacrlevin** 2021-02-21 22:51 UTC
Labels: Need User Test
