### ISSUE TITLE
"An unhandled error has occurred - reload" and app gone from Windows Store

### ISSUE THREAD

**Issue by patrimal** [isaacrlevin/presencelight#587] opened 2022-02-14 23:35 UTC
Getting the above error on 5.0.4.0. I thought I'd try updating, and the Windows Store (the app) says "The think you're looking for isn't here".

**Comment by isaacrlevin** [comment] 2022-02-15 00:53
I am publishing a new version to the store now. In the meantime, can you try the nightly build?
https://presencelight.blob.core.windows.net/nightly/index.html

**Comment by patrimal** [comment] 2022-02-15 20:12
I just realized that the error has to do with the UI only - my lights are still changing colors according to my Teams status, despite the unhandled error.

**Comment by isaacrlevin** [comment] 2022-02-15 21:24
Please provide the latest log file. You can download it from the Log area

**Comment by patrimal** [comment] 2022-02-15 21:38
Uhm... the UI is not loading :) Any other way to access the logs?

**Comment by isaacrlevin** [comment] 2022-02-15 22:12
Logs are located here
C:\Users\{username}\AppData\Local\PresenceLight

**Comment by patrimal** [comment] 2022-02-15 23:35
There's no PresenceLight folder in c:\users\<myursername>\AppData\Local. I am running the Windows Store version (in case that matters).

**Comment by isaacrlevin** [comment] 2022-02-15 23:59
sorry, try something like this

C:\Users\{username}\AppData\Local\Packages\37828IsaacLevin.197278F15330A_zfcjmmeb3zeaa\LocalState\PresenceLight

**Comment by patrimal** [comment] 2022-02-16 00:54
Got it: 
Every time I hit "Reload" in that error, I get a row like this in the log:
[log-2022021516.zip](https://github.com/isaacrlevin/presencelight/files/8075811/log-2022021516.zip)

{"Timestamp":"2022-02-15T16:52:07.2598267-08:00","Level":"Information","MessageTemplate":"Error occured Loading Settings","Properties":{"SourceContext":"PresenceLight.Razor.Pages.Index","Application":"PresenceLight"}}

**Comment by isaacrlevin** [comment] 2022-02-16 16:18
Well that is a bug for something else, should be disregarded. Can you provide your settings file?

C:\Users\{username}}\AppData\Local\Packages\37828IsaacLevin.197278F15330A_zfcjmmeb3zeaa\LocalState\settings.json

**Comment by isaacrlevin** [comment] 2022-02-16 21:05
@patrimal 
Please try the latest nightly and tell me if you have any issues
https://presencelight.blob.core.windows.net/nightly/index.html

**Comment by patrimal** [comment] 2022-02-17 02:44
Here's my settings file (without all the clientIds and secrets):
[settings.zip](https://github.com/isaacrlevin/presencelight/files/8085131/settings.zip)

I have already tried the nightly as you first suggested, and it works. Note that the nightly will "forget" all my settings, so that could be why it works. Can I copy the settings files somewhere so that nightly picks it up?

**Comment by isaacrlevin** [comment] 2022-02-17 16:48
YMMV if you copy the settings but you can try. If you just copy LightSettings, you should be fine. If you delete the LocalState folder (backup settings first) after you uninstall the Store version, restart PC and install the Store version. If it works (without your settings), then the issue is related to your settings and you will have to either enter all the settings again via the App or copy them one by one (which may break the app). 

If you can validate a completely clean version of the store, please let me know.

**Comment by patrimal** [comment] 2022-02-17 18:34
I'm out of town for a few days - will check next week. Thanks for the help!
________________________________

**Comment by isaacrlevin** [comment] 2022-02-24 15:40
@patrimal any updates?

**Comment by patrimal** [comment] 2022-02-24 16:18
Ok, so I uninstalled the Windows version (kept a copy of my settings file) and reinstalled it, and it worked. I then replaced the "new" settings file with my old one, and it broke. So you're right, it's something with my settings file. I'll play around with it some more, as I'd prefer to not lose all my color settings (I had gone down to the activity level), but in the end it's no big deal...

**Comment by isaacrlevin** [comment] 2022-02-24 16:30
You should just be able to copy the "LightSettings" section. Try that

**Comment by isaacrlevin** [comment] 2022-02-24 16:30
Closing this issue

**Closed by isaacrlevin** 2022-02-24 16:30 UTC
Labels: Need User Test

**Comment by jdshkolnik** [comment] 2022-04-05 14:29
I hit the same issue. I fixed it by quitting PresenceLight and setting the AppType value to "Desktop" in settings.json. It was null.

**Comment by patrimal** [comment] 2022-04-05 20:27
Thank you!! That fixed it for me, too!
