### ISSUE TITLE
Unable to list lights for LIFX integration

### ISSUE THREAD

**Issue by chrsmrtn-** [isaacrlevin/presencelight#867] opened 2024-02-14 02:26 UTC
**Describe the bug**
When i click on "Find LIFX Lights", no lights are populated in the dropdown

**To Reproduce**
1. LIFX under configure lights
2. Click on "Get Token"
3. Login to your LIFX account
4. Click on "Find LIFX Lights"
5. Click on the drop down to select a light
6. Note the dropdown does not list any lights

**Expected behavior**
To list lights i've setup with LIFX

**Screenshots**
![Screenshot 2024-02-13 191236](https://github.com/isaacrlevin/presencelight/assets/5657979/61cceec9-d1d1-4310-bb10-f249dd16627f)

## Further details
- OS: Windows 10
- PresenceLight App Type: Desktop
- PresenceLight Build: Store
- PresenceLight Version: 5.8.2
- Did you clear settings.json? (C:\Users\username\AppData\Local\Packages\37828IsaacLevin.197278F15330A.SomeValue\LocalState\settings.json
- No need to, this is a fresh install

**Comment by chrsmrtn-** [comment] 2024-02-15 03:05
Found this error in the logs

`{"Timestamp":"2024-02-14T20:01:41.1406488-07:00","Level":"Information","MessageTemplate":"Get LIFX Lights Initialized","Properties":{"SourceContext":"PresenceLight.Razor.Components.Pages.Lifx","Application":"PresenceLight"}}`
`{"Timestamp":"2024-02-14T20:01:41.5026759-07:00","Level":"Error","MessageTemplate":"Error Occurred Getting LIFX Lights","Exception":"System.NullReferenceException: Object reference not set to an instance of an object.\r\n   at PresenceLight.Razor.Components.Pages.Lifx.CheckLIFX(String type)","Properties":{"SourceContext":"PresenceLight.Razor.Components.Pages.Lifx","Application":"PresenceLight"}}`

**Comment by chrsmrtn-** [comment] 2024-02-15 03:39
Error from nightly build:

`{"Timestamp":"2024-02-14T20:38:23.9062263-07:00","Level":"Information","MessageTemplate":"Get LIFX Lights Initialized","Properties":{"SourceContext":"PresenceLight.Razor.Components.Pages.Lifx","Application":"PresenceLight"}}`
`{"Timestamp":"2024-02-14T20:38:24.2627032-07:00","Level":"Error","MessageTemplate":"Error Occurred Getting LIFX Lights","Exception":"System.NullReferenceException: Object reference not set to an instance of an object.\r\n   at PresenceLight.Razor.Components.Pages.Lifx.CheckLIFX(String type) in D:\\a\\presencelight\\presencelight\\src\\PresenceLight.Razor\\Components\\Pages\\Lifx.razor:line 204","Properties":{"SourceContext":"PresenceLight.Razor.Components.Pages.Lifx","Application":"PresenceLight"}}`

**Comment by chrsmrtn-** [comment] 2024-02-15 03:43
My currently selected item id for LIFX

![image](https://github.com/isaacrlevin/presencelight/assets/5657979/2dd0d1ec-86b0-4200-bdca-983f6be8d547)

**Comment by chrsmrtn-** [comment] 2024-02-15 03:59
Workaround is to use the LIFX api to get the ID of the light you want to use and then manually set the SelectedItemId in the settings to the appropriate encoded value

**Comment by isaacrlevin** [comment] 2024-02-21 00:44
@chrsmrtn- what lights do you have? I wonder if certain lights operate on a different protocol than the ones I have tested with.

**Comment by chrsmrtn-** [comment] 2024-02-24 21:03
LIFX beam and LIFX striplight.  Neither of which are listed in the app

**Comment by isaacrlevin** [comment] 2024-02-24 22:05
So lights or groups don't work?

**Comment by chrsmrtn-** [comment] 2024-02-26 05:03
I''m unable to list lights

**Comment by isaacrlevin** [comment] 2024-02-26 23:52
@chrsmrtn- Can you do me a favor and return the JSON response you get from the LIFX Api?

**Comment by chrsmrtn-** [comment] 2024-03-06 06:21
I'm also unable to list groups

**Comment by isaacrlevin** [comment] 2024-03-06 23:38
I think the issue is with the model of light you have. I have a LIFX Beam, and it shows up in PresenceLight. Here is what that light looks like, only difference I see from yours is the `product_id`

```json
  {
    "id": "xxxxx",
    "uuid": "xxxx",
    "label": "Isaac Wakeup Light",
    "connected": true,
    "power": "on",
    "color": {
      "hue": 191.94,
      "saturation": 1,
      "kelvin": 3500
    },
    "brightness": 0.1,
    "zones": {
      "count": 21,
      "zones": [
        {
          "hue": 191.94,
          "saturation": 1,
          "brightness": 0.1,
          "kelvin": 3500,
          "zone": 0
        },
        {
          "hue": 191.94,
          "saturation": 1,
          "brightness": 0.1,
          "kelvin": 3500,
          "zone": 1
        },
        {
          "hue": 191.94,
          "saturation": 1,
          "brightness": 0.1,
          "kelvin": 3500,
          "zone": 2
        },
        {
          "hue": 191.94,
          "saturation": 1,
          "brightness": 0.1,
          "kelvin": 3500,
          "zone": 3
        },
        {
          "hue": 191.94,
          "saturation": 1,
          "brightness": 0.1,
          "kelvin": 3500,
          "zone": 4
        },
        {
          "hue": 191.94,
          "saturation": 1,
          "brightness": 0.1,
          "kelvin": 3500,
          "zone": 5
        },
        {
          "hue": 191.94,
          "saturation": 1,
          "brightness": 0.1,
          "kelvin": 3500,
          "zone": 6
        },
        {
          "hue": 191.94,
          "saturation": 1,
          "brightness": 0.1,
          "kelvin": 3500,
          "zone": 7
        },
        {
          "hue": 191.94,
          "saturation": 1,
          "brightness": 0.1,
          "kelvin": 3500,
          "zone": 8
        },
        {
          "hue": 191.94,
          "saturation": 1,
          "brightness": 0.1,
          "kelvin": 3500,
          "zone": 9
        },
        {
          "hue": 191.94,
          "saturation": 1,
          "brightness": 0.1,
          "kelvin": 3500,
          "zone": 10
        },
        {
          "hue": 191.94,
          "saturation": 1,
          "brightness": 0.1,
          "kelvin": 3500,
          "zone": 11
        },
        {
          "hue": 191.94,
          "saturation": 1,
          "brightness": 0.1,
          "kelvin": 3500,
          "zone": 12
        },
        {
          "hue": 191.94,
          "saturation": 1,
          "brightness": 0.1,
          "kelvin": 3500,
          "zone": 13
        },
        {
          "hue": 191.94,
          "saturation": 1,
          "brightness": 0.1,
          "kelvin": 3500,
          "zone": 14
        },
        {
          "hue": 191.94,
          "saturation": 1,
          "brightness": 0.1,
          "kelvin": 3500,
          "zone": 15
        },
        {
          "hue": 191.94,
          "saturation": 1,
          "brightness": 0.1,
          "kelvin": 3500,
          "zone": 16
        },
        {
          "hue": 191.94,
          "saturation": 1,
          "brightness": 0.1,
          "kelvin": 3500,
          "zone": 17
        },
        {
          "hue": 191.94,
          "saturation": 1,
          "brightness": 0.1,
          "kelvin": 3500,
          "zone": 18
        },
        {
          "hue": 191.94,
          "saturation": 1,
          "brightness": 0.1,
          "kelvin": 3500,
          "zone": 19
        },
        {
          "hue": 191.94,
          "saturation": 1,
          "brightness": 0.1,
          "kelvin": 3500,
          "zone": 20
        }
      ]
    },
    "effect": "OFF",
    "group": {
      "id": "xxxxxx",
      "name": "OK To Wake"
    },
    "location": {
      "id": "xxxxx",
      "name": "Home"
    },
    "product": {
      "name": "LIFX Beam",
      "identifier": "lifx_beam",
      "company": "LIFX",
      "vendor_id": 1,
      "product_id": 38,
      "capabilities": {
        "has_color": true,
        "has_variable_color_temp": true,
        "has_ir": false,
        "has_hev": false,
        "has_chain": false,
        "has_matrix": false,
        "has_multizone": true,
        "min_kelvin": 2500,
        "max_kelvin": 9000
      }
    },
    "last_seen": "2024-03-06T23:35:06Z",
    "seconds_since_seen": 0
  }
```

**Comment by chrsmrtn-** [comment] 2024-03-07 03:26
So my model is causing the issue with selection but works fine if i manually set the selected light in my config?

**Comment by isaacrlevin** [comment] 2024-03-12 21:59
@chrsmrtn- would you be willing to send me your LIFX token temporarily? I just want to see what that app does when it calls the API

**Comment by isaacrlevin** [comment] 2024-11-01 19:16
@chrsmrtn- I am going to close this. If you are still having issues, feel free to reopen.

**Closed by isaacrlevin** 2024-11-01 19:16 UTC
Labels: Need User Test
