### ISSUE TITLE
Authentication not possible

### ISSUE THREAD

**Issue by Shrekmachine** [isaacrlevin/PresenceLight#109] opened 2020-07-21 10:31 UTC
All settings lost and not maintainable

**Comment by Shrekmachine** [comment] 2020-07-21 10:43
nightly build working fine, but not from Store

**Comment by Shrekmachine** [comment] 2020-07-21 11:44
again not working. I'm not sure what is going on.

**Comment by isaacrlevin** [comment] 2020-07-21 15:57
The new store app requires full uninstall and restart as there are substantial changes to settings.json. Did you try that?

**Comment by Shrekmachine** [comment] 2020-07-21 20:11
Will do, thanks

**Comment by Shrekmachine** [comment] 2020-07-21 20:19
Looks like this is the solution. Works. I just notice once "Configure work hours" is checked, I can't uncheck it

**Comment by isaacrlevin** [comment] 2020-07-21 20:32
got a gif of this? Screen2Gif

**Comment by Shrekmachine** [comment] 2020-07-21 20:39
Nope. Weird, after restarting all settings from the Settings Tab were gone.
But "Configure Hue" was still populated

**Comment by Shrekmachine** [comment] 2020-07-21 20:40
.. and forgot it again after restarting PL

**Comment by isaacrlevin** [comment] 2020-07-27 15:49
@Shrekmachine does latest nightly have this issue?

**Comment by Shrekmachine** [comment] 2020-07-27 17:21
I'm using the Store version, still on 3.05

**Comment by Shrekmachine** [comment] 2020-07-28 07:08
now on 3.0.14.0
Still loosing settings in "Settings"

**Comment by isaacrlevin** [comment] 2020-07-28 21:03
Still an issue on 3.0.19?

**Comment by Shrekmachine** [comment] 2020-07-28 21:12
I will report back once update received via Store

**Comment by isaacrlevin** [comment] 2020-07-29 14:34
Should be updated

**Comment by Shrekmachine** [comment] 2020-07-29 15:23
Version 3.0.19 still not showing values but it seems that it is respecting brightness. When I start PL, lights are dimming even that the fields are empty

**Comment by isaacrlevin** [comment] 2020-07-30 18:38
Is the value that isn't updating just Hue Brightness?

**Comment by Shrekmachine** [comment] 2020-07-30 20:40
![image](https://user-images.githubusercontent.com/8019511/88972361-afe2a080-d2b5-11ea-9d39-c1befd5ce420.png)

**Comment by Shrekmachine** [comment] 2020-07-30 20:41
![image](https://user-images.githubusercontent.com/8019511/88972423-cdb00580-d2b5-11ea-9ebf-3a625e4e5f7c.png)

**Comment by isaacrlevin** [comment] 2020-07-30 21:04
try 3.0.20

**Comment by Shrekmachine** [comment] 2020-07-31 07:41
will wait for the release

**Comment by isaacrlevin** [comment] 2020-07-31 15:39
Release to the store? I need someone to test these changes other than me before I publish to store. I am not using Phillips Hue so I cannot test the HW

**Comment by MatthewMcD** [comment] 2020-08-10 19:00
I just downloaded it from the store and it installs correctly and I can control my Hue lights. The problem is I cannot login. I added a Question about the Side Loading requirement in the Documentation.

**Comment by isaacrlevin** [comment] 2020-08-12 18:26
@Shrekmachine are you still having issues with nightly?

**Comment by Shrekmachine** [comment] 2020-08-12 18:45
Honestly I use only Store version. 3.0.19
Interestingly I do not need to authenticate every time any more.
The issue of not populating the fields is of course not gone with that version.
However, functionality wise it is doing it's job as expected.

**Comment by isaacrlevin** [comment] 2020-09-04 21:28
Closing

**Closed by isaacrlevin** 2020-09-04 21:28 UTC
Labels: question

**Comment by Shrekmachine** [comment] 2020-09-05 07:11
when will the 3.0.20 dropped to the store? Then I can test :)

**Comment by isaacrlevin** [comment] 2020-09-06 00:45
I will probably push soon
