### ISSUE TITLE
Sign in never stops....

### ISSUE THREAD

**Issue by renhammington** [isaacrlevin/presencelight#550] opened 2022-01-11 21:50 UTC
I love the idea of this app... you have no idea how many times people have walked into my room when I've been in the middle of an important call with clients. Can't wait to get this working.

Having problems with the sign in. I've signed in successfully via the browser popup, but the sign in tab in the app doesn't change from "If you are adding new lights, this may take up to a minute". It's been much longer than that now and it's still showing the progress indicator.

![image](https://user-images.githubusercontent.com/4220483/149026891-516b7491-cc7f-40c0-9093-ba18b4095654.png)

**Comment by isaacrlevin** [comment] 2022-01-11 23:12
Can you please fill out the form?

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.


## Further details
- OS: [e.g. iOS]
- PresenceLight App Type (Desktop, Blazor)
- PresenceLight Build (Nightly, Store, etc)
- PresenceLight Version (The # in About)
- Did you clear settings.json? (C:\Users\username\AppData\Local\Packages\37828IsaacLevin.197278F15330A.SomeValue\LocalState\settings.json
- ASP.NET Core version

**Comment by isaacrlevin** [comment] 2022-01-11 23:14
Also if there are any notes in the Logs tab, please provide

**Comment by darrenlock** [comment] 2022-01-15 11:32
I have the same issue. New install today from Microsoft Store. I have connected to Hue Bridge and configure light OK but when starting the app presented with the screen shot above. When I first installed the app I was prompted for my 365 authentication (web pop-up) which appeared to work ok.
- Windows 10 Pro
- Version	21H1
- OS build	19043.1466
- Experience	Windows Feature Experience Pack 120.2212.3920.0
![image](https://user-images.githubusercontent.com/19533550/149620250-a25dd08b-2d04-4958-a698-a39cd8c9d67c.png)

**Comment by darrenlock** [comment] 2022-01-15 11:34
Delete settings.json but still the same problem

**Comment by darrenlock** [comment] 2022-01-15 11:41
{"Timestamp":"2022-01-15T11:02:19.5359988+00:00","Level":"Information","MessageTemplate":"Getting Graph Data: Profle, Image, Presence - GraphWrapper:GetBatchContent Line: 86","Properties":{"SourceContext":"PresenceLight.Core.GraphWrapper","LineNumber":86,"FilePath":"D:\\a\\presencelight\\presencelight\\src\\PresenceLight.Core\\GraphServices\\GraphWrapper.cs","MemberName":"GetBatchContent","Application":"PresenceLight"}}
{"Timestamp":"2022-01-15T11:02:30.5252842+00:00","Level":"Error","MessageTemplate":"Error Occured Getting Batch Content from Graph Api - GraphWrapper:GetBatchContent Line: 106","Exception":"Status Code: Forbidden\r\nMicrosoft.Graph.ServiceException: Code: Authorization_RequestDenied\r\nMessage: Insufficient privileges to complete the operation.\r\nInner error:\r\n\tAdditionalData:\r\n\tdate: 2022-01-15T11:02:31\r\n\trequest-id: 5bbc72d0-3d82-4d2a-8ccb-10e254350525\r\n\tclient-request-id: 5bbc72d0-3d82-4d2a-8ccb-10e254350525\r\n\r\n   at Microsoft.Graph.BatchResponseContent.ValidateSuccessfulResponse(HttpResponseMessage httpResponseMessage)\r\n   at Microsoft.Graph.BatchResponseContent.GetResponseByIdAsync[T](String requestId)\r\n   at PresenceLight.Core.GraphWrapper.GetBatchContent(CancellationToken token)","Properties":{"SourceContext":"PresenceLight.Core.GraphWrapper","LineNumber":106,"FilePath":"D:\\a\\presencelight\\presencelight\\src\\PresenceLight.Core\\GraphServices\\GraphWrapper.cs","MemberName":"GetBatchContent","Application":"PresenceLight"}}

**Comment by isaacrlevin** [comment] 2022-01-17 03:22
Looks like the app doesn't have the access to your info. Your company might need to give consent to it.

**Comment by renhammington** [comment] 2022-01-17 03:47
Mines working now. Potentially a delay between changing settings and
working.

**Comment by isaacrlevin** [comment] 2022-01-17 17:35
@darrenlock

**Comment by isaacrlevin** [comment] 2022-01-19 18:36
Closing as issue creator no longer has issue. If anyone has similar issues, open a new issue.

**Closed by isaacrlevin** 2022-01-19 18:36 UTC
