### ISSUE TITLE
After update, settings are gone

### ISSUE THREAD

**Issue by LucVanDyck** [isaacrlevin/presencelight#515] opened 2021-12-04 15:55 UTC
I just updated to version 4.3.1.0. Now all settings in "Configure Custom API" tab are gone. Wasn't it possible to retain them?

Update was done through Chocolatey. Had to exit the program first, otherwise some files were locked.

**Comment by isaacrlevin** [comment] 2021-12-14 00:39
I believe Choco does an uninstall than install again, so it would make sense it got deleted. That is a bad experience. I will chat with some folks on how to make it better

**Comment by isaacrlevin** [comment] 2021-12-14 00:43
@steviecoaster is there a best practice on persisting settings when running choco update?

**Comment by gep13** [comment] 2021-12-20 22:31
@isaacrlevin the short answer...  it depends 😄 

Since the chocolateyInstall and chocolateyUninstall files are PowerShell, you can do anything that you want.

I am assuming that a config file is created/stored beside the running executable for presencelight, is that correct?

If so, you might want to start using the beforeModify script (document in part in here: https://docs.chocolatey.org/en-us/create/create-packages#during-which-scenarios-will-my-custom-scripts-be-triggered) to check for the presence of this file, and if found, copy/move the file to another location, and then copy it back again if found during the installation?

**Comment by isaacrlevin** [comment] 2021-12-20 22:42
So something like this

1. Look for current version of file, if it is there, move to a temp location
2. Do uninstall/install steps
3. Move file back from temp location of exe

Does that sound right? Can this just be in chocolateyInstall.ps1 or does it HAVE TO BE in chocolateyBeforeModify.ps1?

**Comment by gep13** [comment] 2021-12-21 10:44
@LucVanDyck I have not been able to reproduce the problem that you are seeing.  The steps I have taken are the following:

* Install an older version of PresenceLight `choco install presencelight --version 4.2.35.0`
* Open PresenceLight and add some information to the Configure Custom API section
* Exit PresenceLight
* Open it up again to ensure that the values are persisted, and they were
* Exit PresenceLight
* Update to the latest version of PresenceLight `choco upgrade presencelight`
* Open it up to ensure that the values are persisted, and they were

Can you please confirm what version of the Chocolatey package that you updated from?

@isaacrlevin I don't actually think that there is anything to do here, as the persistence of the settings is "working as expected".

There are some related issues, that I think need to be addressed. Specifically this issue that @LucVanDyck mentioned:

> Had to exit the program first, otherwise some files were locked.

But I think this should be raised as a separate issue.  Happy to submit a PR to address this if you would like me to.

**Comment by LucVanDyck** [comment] 2021-12-21 10:59
I updated from 4.2.35 to 4.3.1

**Comment by gep13** [comment] 2021-12-21 11:06
Did you install PresenceLight to a custom location (either during the initial installation, or during the upgrade)? Or did you essentially use the steps that I outlined above?

**Comment by LucVanDyck** [comment] 2021-12-21 11:13
Didn't change the location during setup or upgrade. 

I first had installed PresenceLight via their Windows installer. After some weeks I found out it was also available as Chocolatey package, so I uninstalled PresenceLight, installed it via Chocolatey GUI and did the setup (version 4.2.35). Some weeks later version 4.3.1 became available which was upgraded through Chocolatey GUI.

I have PresenceLight running in the background (Start Minimized option). Maybe the message about files being locked is related to that?

**Comment by gep13** [comment] 2021-12-21 13:28
>@LucVanDyck said...
Maybe the message about files being locked is related to that?

I initially got the same error, but re-attempting the upgrade made things work, and again, the settings.json file remained in place.  The Chocolatey installation is essentially just an extraction of the release zip file into the target directory, nothing actually is being uninstalled, but rather replaced with the new files.  So the settings.json file should remain, as it did for me, during the upgrade operation.

I cannot explain why this didn't work for you during the upgrade operation.

I would be curious, if you had the time, if you could attempt to repeat the operation to see if it did the same thing again.

**Comment by LucVanDyck** [comment] 2021-12-21 13:35
I'll let you know with the next update, when the settings are removed again.

**Comment by isaacrlevin** [comment] 2021-12-21 18:58
@gep13 more than happy to review a PR on fixing the issue described here. Closing for now. @LucVanDyck please re-open if the issue reoccurs when you update

**Comment by LucVanDyck** [comment] 2022-01-03 14:05
Today I tried to upgrade from 4.3.1.0 -> 4.4.1.0 through Chocolatey GUI. 
When PresenceLight is running in the tray during the upgrade, following errors occur:

![Capture](https://user-images.githubusercontent.com/7642164/147939782-de61bcd9-4cff-4e72-a69c-48f3086bd3b2.jpg)

When PresenceLight is exited, then the upgrade through Chocolatey works fine.

**Comment by isaacrlevin** [comment] 2022-01-03 18:06
This should be fixed with the changes by @gep13 going forward. Did the settings persist?

**Comment by gep13** [comment] 2022-01-03 18:09
@isaacrlevin has a new version been released since the changes that I made?

**Comment by LucVanDyck** [comment] 2022-01-03 19:02
> This should be fixed with the changes by @gep13 going forward. Did the settings persist?

Yes, the settings were not lost.

**Closed** 2022-01-12 21:58 UTC
